-- Gift Card Manager
-- Role-based version with audit log.
-- Run this in the Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  role text not null default 'viewer'
    check (role in ('admin', 'manager', 'viewer')),
  created_at timestamptz not null default now()
);

create table if not exists public.gift_cards (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  pin text not null,
  value numeric(12,2) not null check (value > 0),
  currency varchar(3) not null check (currency = upper(currency)),
  status text not null default 'available'
    check (status in ('available', 'used')),
  batch_label text,
  recipient text,
  note text,
  used_at timestamptz,
  used_by text,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid()
);

create table if not exists public.gift_card_audit_log (
  id bigint generated always as identity primary key,
  gift_card_id uuid,
  action text not null,
  actor_id uuid,
  actor_email text,
  old_data jsonb,
  new_data jsonb,
  created_at timestamptz not null default now()
);

create index if not exists gift_cards_status_idx on public.gift_cards(status);
create index if not exists gift_cards_currency_idx on public.gift_cards(currency);
create index if not exists gift_cards_created_at_idx on public.gift_cards(created_at desc);
create index if not exists gift_card_audit_card_idx on public.gift_card_audit_log(gift_card_id);
create index if not exists gift_card_audit_created_idx on public.gift_card_audit_log(created_at desc);

-- Automatically create a viewer profile for new users.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, role)
  values (
    new.id,
    lower(coalesce(new.email, '')),
    case
      when lower(coalesce(new.email, '')) = 'dan.mangold@on-running.com' then 'admin'
      else 'viewer'
    end
  )
  on conflict (id) do update
    set email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert or update of email on auth.users
for each row execute procedure public.handle_new_user();

-- Backfill profiles for users that already exist.
insert into public.profiles (id, email, role)
select
  id,
  lower(coalesce(email, '')),
  case
    when lower(coalesce(email, '')) = 'dan.mangold@on-running.com' then 'admin'
    else 'viewer'
  end
from auth.users
on conflict (id) do update
set email = excluded.email,
    role = case
      when excluded.email = 'dan.mangold@on-running.com' then 'admin'
      else public.profiles.role
    end;

-- Explicitly ensure Dan is admin.
update public.profiles
set role = 'admin'
where email = 'dan.mangold@on-running.com';

create or replace function public.current_role()
returns text
language sql
stable
security definer set search_path = public
as $$
  select coalesce(
    (select role from public.profiles where id = auth.uid()),
    'viewer'
  );
$$;

-- Immutable audit trail generated by the database, not by the browser.
create or replace function public.audit_gift_card_changes()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  email_value text;
begin
  select email into email_value
  from public.profiles
  where id = auth.uid();

  if tg_op = 'INSERT' then
    insert into public.gift_card_audit_log
      (gift_card_id, action, actor_id, actor_email, old_data, new_data)
    values
      (new.id, 'created', auth.uid(), email_value, null, to_jsonb(new));
    return new;
  elsif tg_op = 'UPDATE' then
    insert into public.gift_card_audit_log
      (gift_card_id, action, actor_id, actor_email, old_data, new_data)
    values
      (
        new.id,
        case
          when old.status = 'available' and new.status = 'used' then 'marked_used'
          when old.status = 'used' and new.status = 'available' then 'restored'
          else 'updated'
        end,
        auth.uid(),
        email_value,
        to_jsonb(old),
        to_jsonb(new)
      );
    return new;
  end if;

  return null;
end;
$$;

drop trigger if exists gift_card_audit_trigger on public.gift_cards;
create trigger gift_card_audit_trigger
after insert or update on public.gift_cards
for each row execute procedure public.audit_gift_card_changes();

alter table public.profiles enable row level security;
alter table public.gift_cards enable row level security;
alter table public.gift_card_audit_log enable row level security;

-- Profiles: users can see their own role; admins can see all profiles.
create policy "users read own profile"
on public.profiles for select to authenticated
using (id = auth.uid() or public.current_role() = 'admin');

-- Gift cards:
-- Viewer: read only
-- Manager: read, add, mark used / restore
-- Admin: same plus access to audit log and future admin functions
create policy "authenticated users read gift cards"
on public.gift_cards for select to authenticated
using (true);

create policy "managers and admins add gift cards"
on public.gift_cards for insert to authenticated
with check (public.current_role() in ('manager', 'admin'));

create policy "managers and admins update gift cards"
on public.gift_cards for update to authenticated
using (public.current_role() in ('manager', 'admin'))
with check (public.current_role() in ('manager', 'admin'));

-- Deliberately no DELETE policy.

-- Audit log is read-only from the application and visible only to admins.
create policy "admins read audit log"
on public.gift_card_audit_log for select to authenticated
using (public.current_role() = 'admin');

-- No INSERT / UPDATE / DELETE policies for audit_log.
-- Entries are written only by the security-definer database trigger.
